### ISSUE TITLE
[Training] AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by snowymo** [nex-mpi/nex-code#9]
Hi,

I am trying running nex on my machine (windows, RTX2080).

After I created the conda env via environment.tml, I first received this error when run the training code: 
1) OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/

Then I set the variable KMP_DUPLICATE_LIB_OK to true and rerun. Now I received the second error:
2) AssertionError: Torch not compiled with CUDA enabled.

I looked up online and all suggested to install torch and torchvision via conda but in envirnoment.yml authors noted to install via pip ```conda give error about cuda. So, we install torch via pip instead.```

Any idea?

**Comment by pureexe** [comment]
I can run the nex code on a Windows machine without any error. 

![image](https://user-images.githubusercontent.com/1303847/117419591-f650e400-af46-11eb-8def-5c47e3aed8d7.png)

## OMP Error
I have no idea. We don't have any intel machine here. So, sorry about that. 

## CUDA error
As it says you need CUDA.

Please follow the instruction that describe in Tensorflow [GPU support](https://www.tensorflow.org/install/gpu) page.
![image](https://user-images.githubusercontent.com/1303847/117419439-c30e5500-af46-11eb-869a-fb1b8ec50951.png)

Then, you install torch via pip installation command as suggest in [pytorch](https://pytorch.org/) page

![image](https://user-images.githubusercontent.com/1303847/117419931-49c33200-af47-11eb-88bd-b7561b61a69f.png)

By the way, we prefer to use Linux (especially ubuntu) to avoid a headache problem like this.

**Comment by snowymo** [comment]
I install the environment via conda instead of pip (which is specified in environment.yml) and it works.

Thanks
